### ISSUE TITLE
Inclusion Dependencies using SPIDER or FAIDA using Python

### ISSUE THREAD

**Issue by urvish-stat** [Desbordante/desbordante-core#427]

**Comment by chernishev** [comment]
Hi! I'm not quite understand your issue, since we already support inclusion dependencies in Python (for both Spider and Faida). Check this example:
https://github.com/Desbordante/desbordante-core/blob/main/examples/mining_ind.py

**Comment by chernishev** [comment]
> Thank you for quick response! I can't access the Python package in windows. I believe it is only accessible in Linux.   On Wednesday 12 June 2024 at 03:53:02 pm GMT+5:30, George Chernishev ***@***.***> wrote: Hi! I'm not quite understand your issue, since we already support inclusion dependencies in Python (for both Spider and Faida). Check this example: https://github.com/Desbordante/desbordante-core/blob/main/examples/mining_ind.py — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Yes, for now we are linux-only.
